version: '3.3'
services:
  application:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/godtask
    ports:
      - "8080:8080"

  db:
    image: postgres:14-alpine3.14
    restart: always
    environment:
      POSTGRES_DB: 'godtask'
      POSTGRES_USER: 'godtask'
      POSTGRES_PASSWORD: 'godtask'
    ports:
      - "5432:5432"
    expose:
      - "5432"
